apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/clusterrolebindings/openshift-gitops-openshift-gitops-argocd-application-controller-admin/kustomization.yaml
  - ../../base/namespaces/oai-demo/kustomization.yaml
  - clusterversion.yml
