apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/core/namespaces/democratic-csi/
  - ../../base/core/namespaces/oai-demo/
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-controller-rb/
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-node-rb/
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/openshift-gitops-openshift-gitops-argocd-application-controller-admin/
  - ../../base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-controller-cr/
  - ../../base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-node-cr/
  - ../../base/storage.k8s.io/csidrivers/org.democratic-csi.nfs/
  - ../../base/storage.k8s.io/storageclasses/moc-nfs-csi/
  - clusterversion.yml
